/**
 * Site-wide configuration: navigation, credibility labels and the reference
 * list used across the interface.
 *
 * Credibility labels follow the project's anti-hallucination rule:
 *  [VERIFIED]   supported by an authoritative source
 *  [SIMULATED]  generated by the demonstration itself
 *  [ASSUMPTION] a design assumption made for the prototype
 *  [PROPOSED]   a future implementation idea, not built
 */

export const SITE = {
  name: "Drishti-Optik",
  tagline: "AI-Based Virtual Camera Tracking for Mobile FSOC Terminals",
  shortDescription:
    "Computer-vision-assisted coarse alignment for mobile free-space optical communication terminals.",
  statusBadge: "Prototype • Simulation Environment",
  organisation: "Indian Space Research Organisation (ISRO) problem statement",
  problemStatementId: "SIH26171",
  /** Canonical base used for canonical URLs, OG tags and the sitemap. */
  canonicalBase: "https://drishti-optik.example",
  contactNote:
    "Project contact details will be provided by the development team. The contact form below reaches the Drishti-Optik prototype team only.",
} as const;

export type CredibilityLabel =
  | "VERIFIED"
  | "SIMULATED"
  | "ASSUMPTION"
  | "PROPOSED";

export const CREDIBILITY_COPY: Record<
  CredibilityLabel,
  { meaning: string; tone: "ok" | "sim" | "assume" | "future" }
> = {
  VERIFIED: {
    meaning: "Supported by an authoritative source listed in References.",
    tone: "ok",
  },
  SIMULATED: {
    meaning: "Generated by the Drishti-Optik demonstration environment.",
    tone: "sim",
  },
  ASSUMPTION: {
    meaning: "A design assumption made for this prototype, not a measurement.",
    tone: "assume",
  },
  PROPOSED: {
    meaning: "A future implementation idea. Not part of the current build.",
    tone: "future",
  },
};

export interface NavItem {
  label: string;
  href: string;
  /** Shown in the mobile sheet only when true. */
  primary?: boolean;
}

export const PRIMARY_NAV: NavItem[] = [
  { label: "Home", href: "/", primary: true },
  { label: "Technology", href: "/technology", primary: true },
  { label: "Simulation", href: "/console", primary: true },
  { label: "Architecture", href: "/architecture" },
  { label: "Documentation", href: "/documentation" },
  { label: "About", href: "/about" },
];

export interface Reference {
  id: string;
  label: CredibilityLabel;
  title: string;
  publisher: string;
  href: string;
  note: string;
}

/**
 * References used for factual claims. Every entry below was located during
 * research; nothing in the running text is invented.
 */
export const REFERENCES: Reference[] = [
  {
    id: "ref-isro-contact",
    label: "VERIFIED",
    title: "ISRO official contact page",
    publisher: "Indian Space Research Organisation",
    href: "https://www.isro.gov.in/contact.html",
    note: "Source for ISRO Headquarters' public address and contact details.",
  },
  {
    id: "ref-isro-hq",
    label: "VERIFIED",
    title: "Department of Space and ISRO Headquarters",
    publisher: "Indian Space Research Organisation",
    href: "https://www.isro.gov.in/DOS&ISROHQ.html",
    note: "Authoritative source for ISRO organisational information used on the About page.",
  },
  {
    id: "ref-kaymak",
    label: "VERIFIED",
    title:
      "A Survey on Acquisition, Tracking, and Pointing Mechanisms for Mobile Free-Space Optical Communications",
    publisher: "IEEE Communications Surveys & Tutorials (Kaymak, Rojas-Cessa et al.)",
    href: "https://web.njit.edu/~rojasces/publications/2018kayrocomst.pdf",
    note: "Establishes the ATP/PAT terminology and the coarse-then-fine acquisition sequence.",
  },
  {
    id: "ref-abdelfatah",
    label: "VERIFIED",
    title:
      "A review on pointing, acquisition, and tracking approaches in free-space optical communications",
    publisher: "Optical and Quantum Electronics, Springer (Abdelfatah et al., 2022)",
    href: "https://link.springer.com/article/10.1007/s11082-022-03968-2",
    note: "Background on pointing error, beam divergence and alignment tolerance in FSO links.",
  },
  {
    id: "ref-sun",
    label: "VERIFIED",
    title:
      "High-Precision Tracking of Free-Space Optical Communication for Moving Platforms",
    publisher: "Photonics, MDPI (Sun et al., 2024)",
    href: "https://www.mdpi.com/2304-6732/11/10/900",
    note: "Recent work on tracking moving platforms with optical terminals.",
  },
  {
    id: "ref-sda",
    label: "VERIFIED",
    title: "Optical Communications Terminal Standard, Version 3.0",
    publisher: "U.S. Space Development Agency",
    href: "https://www.sda.mil/wp-content/uploads/2022/04/SDA-OCT-Standard-v3.0.pdf",
    note: "Public technical reference for PAT terminology and acquisition/tracking concepts.",
  },
  {
    id: "ref-prototype",
    label: "ASSUMPTION",
    title: "Drishti-Optik prototype parameter set",
    publisher: "Drishti-Optik development team",
    href: "/documentation#simulation-parameters",
    note:
      "Field of view, slew rate, tolerance and pixel mapping used by the simulation. Demonstration values only — not measured hardware results.",
  },
];

export const DISCLAIMERS = {
  notIsro:
    "Drishti-Optik is an independent prototype software concept developed around the stated problem statement. It is not developed, endorsed, certified or deployed by ISRO unless stated by an official ISRO source.",
  simulation:
    "Every numeric reading shown in the console is produced by the Drishti-Optik simulation. It is a demonstration value and not a measured hardware result.",
  noControl:
    "This software does not connect to, command or control any physical optical terminal or spacecraft.",
} as const;
