import { useEffect, useRef, useState } from "react";

/** Lifecycle of the optional real camera input. */
export type CameraFeedStatus =
  | "off"
  | "requesting"
  | "active"
  | "denied"
  | "unsupported";

export interface CameraFeed {
  /** Attach to a `<video muted playsInline>` element; null while off. */
  videoRef: React.RefObject<HTMLVideoElement | null>;
  status: CameraFeedStatus;
  /** True only while a real camera stream is delivering frames. */
  live: boolean;
  /** Operator-facing explanation of the current status. */
  message: string;
}

const MESSAGES: Record<CameraFeedStatus, string> = {
  off: "Simulated sensor active — the overlay values below are generated by the simulation engine.",
  requesting: "Requesting camera permission… the simulation continues until a stream arrives.",
  active:
    "Camera input active. The overlay geometry and every numeric readout remain SIMULATED values.",
  denied:
    "Camera permission denied — falling back to the simulated sensor feed.",
  unsupported:
    "No camera interface available in this browser — using the simulated sensor feed.",
};

/**
 * Optional real camera input for the virtual sensor viewport.
 *
 * The simulation is the source of truth either way: this hook only decides
 * whether a live video layer is drawn *behind* the overlay. If the browser has
 * no camera, permission is refused, or the request fails, it degrades to the
 * simulated feed and says so rather than throwing.
 */
export function useCameraFeed(enabled: boolean): CameraFeed {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const [stream, setStream] = useState<MediaStream | null>(null);
  const [status, setStatus] = useState<CameraFeedStatus>("off");

  useEffect(() => {
    if (!enabled) {
      setStatus("off");
      setStream(null);
      return;
    }

    const media =
      typeof navigator !== "undefined" ? navigator.mediaDevices : undefined;
    if (!media?.getUserMedia) {
      setStatus("unsupported");
      return;
    }

    let cancelled = false;
    setStatus("requesting");

    media
      .getUserMedia({ video: { facingMode: "environment" }, audio: false })
      .then((next) => {
        if (cancelled) {
          next.getTracks().forEach((track) => track.stop());
          return;
        }
        setStream(next);
        setStatus("active");
      })
      .catch(() => {
        if (cancelled) return;
        setStatus("denied");
      });

    return () => {
      cancelled = true;
    };
  }, [enabled]);

  // Release the hardware when the stream is replaced or the view unmounts.
  useEffect(() => {
    return () => {
      stream?.getTracks().forEach((track) => track.stop());
    };
  }, [stream]);

  // Bind the stream to whichever <video> element is mounted.
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    if (stream) {
      video.srcObject = stream;
      void video.play().catch(() => {
        /* Autoplay can be blocked; the simulated layer still renders. */
      });
    } else {
      video.srcObject = null;
    }
  }, [stream, status, enabled]);

  return {
    videoRef,
    status,
    live: status === "active",
    message: MESSAGES[status],
  };
}
