import { StatusDot } from "@/components/common/Tags";
import { SIM, STATUS_COPY, type Telemetry, type TrackingStatus } from "@/lib/tracking-engine";
import { cn } from "@/lib/utils";
import { motion, useReducedMotion } from "framer-motion";
import { Crosshair, Focus, ScanLine } from "lucide-react";

/**
 * The simulated camera feed.
 *
 * Everything drawn here is generated by the simulation engine. The viewport is
 * a virtual sensor: the overlay geometry is derived from the same telemetry the
 * numeric panels read, so the picture and the numbers always agree.
 */
export function CameraViewport({
  telemetry,
  status,
  frameId,
  cameraAzimuth,
  cameraElevation,
}: {
  telemetry: Telemetry;
  status: TrackingStatus;
  frameId: string;
  cameraAzimuth: number;
  cameraElevation: number;
}) {
  const reduced = useReducedMotion();
  const copy = STATUS_COPY[status];
  const centreX = telemetry.center.x;
  const centreY = telemetry.center.y;
  const offsetX = telemetry.offsetPx.x;
  const offsetY = telemetry.offsetPx.y;
  const centreOfFrame = { x: SIM.frameWidth / 2, y: SIM.frameHeight / 2 };

  return (
    <figure className="flex flex-col gap-3">
      <div
        className={cn(
          "clay-screen relative isolate overflow-hidden",
          "aspect-video w-full",
        )}
      >
        {/* Virtual sensor backdrop */}
        <div
          className="absolute inset-0"
          aria-hidden="true"
          style={{
            background:
              "radial-gradient(120% 90% at 50% 12%, color-mix(in oklch, var(--hud-cyan) 12%, transparent), transparent 60%), radial-gradient(90% 70% at 20% 100%, color-mix(in oklch, var(--hud-violet) 14%, transparent), transparent 65%), linear-gradient(180deg, oklch(0.235 0.038 266), oklch(0.19 0.032 266))",
          }}
        />

        {/* Radar-style reference rings */}
        <svg
          className="absolute inset-0 size-full opacity-[0.5]"
          viewBox="0 0 640 360"
          preserveAspectRatio="none"
          aria-hidden="true"
        >
          {[60, 120, 180].map((r) => (
            <circle
              key={r}
              cx={centreOfFrame.x}
              cy={centreOfFrame.y}
              r={r}
              fill="none"
              stroke="color-mix(in oklch, var(--hud-cyan) 30%, transparent)"
              strokeWidth={0.8}
              strokeDasharray="5 9"
            />
          ))}
          {Array.from({ length: 9 }).map((_, index) => (
            <line
              key={`v-${index}`}
              x1={index * 80}
              y1={0}
              x2={index * 80}
              y2={360}
              stroke="color-mix(in oklch, var(--hud-cyan) 16%, transparent)"
              strokeWidth={0.6}
            />
          ))}
          {Array.from({ length: 5 }).map((_, index) => (
            <line
              key={`h-${index}`}
              x1={0}
              y1={index * 90}
              x2={640}
              y2={index * 90}
              stroke="color-mix(in oklch, var(--hud-cyan) 16%, transparent)"
              strokeWidth={0.6}
            />
          ))}
          <line
            x1={centreOfFrame.x}
            y1={0}
            x2={centreOfFrame.x}
            y2={360}
            stroke="color-mix(in oklch, var(--hud-cyan) 55%, transparent)"
            strokeWidth={0.9}
          />
          <line
            x1={0}
            y1={centreOfFrame.y}
            x2={640}
            y2={centreOfFrame.y}
            stroke="color-mix(in oklch, var(--hud-cyan) 55%, transparent)"
            strokeWidth={0.9}
          />
        </svg>

        <div className="hud-scanlines absolute inset-0 opacity-60" aria-hidden="true" />

        {/* Acquisition sweep while the target is outside the frame centre */}
        {telemetry.inFov && status !== "aligned" && !reduced && (
          <motion.div
            aria-hidden="true"
            className="absolute left-1/2 top-1/2 size-[520px] -translate-x-1/2 -translate-y-1/2 rounded-full"
            style={{
              background:
                "conic-gradient(from 0deg, color-mix(in oklch, var(--hud-cyan) 22%, transparent), transparent 40%)",
            }}
            animate={{ rotate: 360 }}
            transition={{ duration: 6, repeat: Infinity, ease: "linear" }}
          />
        )}

        {/* Sensor geometry */}
        {telemetry.inFov && (
          <svg
            className="absolute inset-0 size-full"
            viewBox="0 0 640 360"
            preserveAspectRatio="none"
            aria-hidden="true"
          >
            <line
              x1={centreOfFrame.x}
              y1={centreOfFrame.y}
              x2={centreX}
              y2={centreY}
              stroke="color-mix(in oklch, var(--hud-violet) 85%, white)"
              strokeWidth={1.6}
              strokeDasharray="6 5"
            />
            <rect
              x={telemetry.bbox.x}
              y={telemetry.bbox.y}
              width={telemetry.bbox.width}
              height={telemetry.bbox.height}
              fill="color-mix(in oklch, var(--chart-4) 12%, transparent)"
              stroke="color-mix(in oklch, var(--chart-4) 78%, white)"
              strokeWidth={2}
              rx={10}
            />
            {[
              [0, 0, 1, 0],
              [0, 0, 0, 1],
              [1, 0, 0, 0],
              [0, 1, 0, 0],
            ].map(([ax, ay, bx, by], index) => (
              <line
                key={index}
                x1={telemetry.bbox.x + ax * 26}
                y1={telemetry.bbox.y + ay * 26}
                x2={telemetry.bbox.x + bx * 34}
                y2={telemetry.bbox.y + by * 34}
                stroke="color-mix(in oklch, var(--chart-4) 92%, white)"
                strokeWidth={2.4}
              />
            ))}
            <circle
              cx={centreX}
              cy={centreY}
              r={4}
              fill="color-mix(in oklch, var(--chart-4) 92%, white)"
            />
            <circle
              cx={centreX}
              cy={centreY}
              r={11}
              fill="none"
              stroke="color-mix(in oklch, var(--chart-4) 70%, white)"
              strokeWidth={1.2}
            />
          </svg>
        )}

        {/* Frame-centre crosshair */}
        <svg
          className="pointer-events-none absolute inset-0 size-full"
          viewBox="0 0 640 360"
          preserveAspectRatio="none"
          aria-hidden="true"
        >
          <circle
            cx={centreOfFrame.x}
            cy={centreOfFrame.y}
            r={26}
            fill="none"
            stroke="color-mix(in oklch, var(--hud-cyan) 70%, white)"
            strokeWidth={1.4}
          />
          <line
            x1={centreOfFrame.x - 12}
            y1={centreOfFrame.y}
            x2={centreOfFrame.x + 12}
            y2={centreOfFrame.y}
            stroke="color-mix(in oklch, var(--hud-cyan) 85%, white)"
            strokeWidth={1.4}
          />
          <line
            x1={centreOfFrame.x}
            y1={centreOfFrame.y - 12}
            x2={centreOfFrame.x}
            y2={centreOfFrame.y + 12}
            stroke="color-mix(in oklch, var(--hud-cyan) 85%, white)"
            strokeWidth={1.4}
          />
          {/* Corner brackets */}
          <path
            d="M18 46V18h28M594 18h28v28M622 314v28h-28M46 342H18v-28"
            fill="none"
            stroke="color-mix(in oklch, var(--hud-cyan) 45%, white)"
            strokeWidth={2}
          />
        </svg>

        {/* Tracking point readout, anchored to the estimated target centre */}
        {telemetry.inFov && (
          <motion.div
            className="absolute"
            style={{ x: "-50%" }}
            animate={{
              left: `${(centreX / SIM.frameWidth) * 100}%`,
              top: `${(centreY / SIM.frameHeight) * 100}%`,
            }}
            transition={{ duration: reduced ? 0 : 1 / SIM.fps, ease: "linear" }}
          >
            <div className="translate-y-[14px] whitespace-nowrap rounded-full bg-[color-mix(in_oklch,var(--chart-4)_82%,black)] px-2 py-0.5 font-mono text-[9.5px] font-semibold tracking-wide text-white">
              {frameId} · {Math.round(telemetry.confidence * 100)}%
            </div>
          </motion.div>
        )}

        {/* HUD chrome */}
        <div className="pointer-events-none absolute inset-0 p-3 sm:p-4">
          <div className="flex items-start justify-between gap-3">
            <div className="flex flex-col gap-1.5 text-left">
              <span className="hud-label !text-[9.5px] !text-[color-mix(in_oklch,var(--hud-cyan)_85%,white)]">
                Virtual sensor feed
              </span>
              <span className="flex items-center gap-2 font-mono text-[10.5px] uppercase tracking-widest text-white/85">
                <StatusDot tone={copy.tone} pulse={status !== "idle" && status !== "aligned"} />
                {copy.label}
              </span>
            </div>
            <div className="flex flex-col items-end gap-1.5">
              <span className="rounded-full border border-dashed border-[color-mix(in_oklch,var(--chart-5)_60%,transparent)] px-2 py-0.5 font-mono text-[9px] uppercase tracking-[0.14em] text-[color-mix(in_oklch,var(--chart-5)_85%,white)]">
                Simulated values
              </span>
              <span className="font-mono text-[10px] text-white/70">
                {SIM.frameWidth}×{SIM.frameHeight} · {SIM.fps} fps (sim)
              </span>
            </div>
          </div>

          {!telemetry.inFov && (
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="flex flex-col items-center gap-2 text-center">
                <ScanLine className="size-6 text-[color-mix(in_oklch,var(--hud-cyan)_80%,white)]" aria-hidden="true" />
                <p className="font-mono text-[11px] uppercase tracking-[0.16em] text-white/85">
                  {status === "idle" ? "Sensor idle" : "Target outside field of view"}
                </p>
                <p className="max-w-[15rem] text-[11px] leading-4 text-white/60">
                  {status === "idle"
                    ? "Start tracking to begin the simulated acquisition sequence."
                    : "Coarse re-point required. Use re-centre or auto align."}
                </p>
              </div>
            </div>
          )}

          <div className="absolute bottom-3 left-3 flex flex-col gap-1 sm:bottom-4 sm:left-4">
            <span className="flex items-center gap-1.5 font-mono text-[9.5px] uppercase tracking-[0.14em] text-white/55">
              <Focus className="size-3" aria-hidden="true" /> Boresight ΔX {offsetX.toFixed(1)} · ΔY{" "}
              {offsetY.toFixed(1)} px
            </span>
            <span className="flex items-center gap-1.5 font-mono text-[9.5px] uppercase tracking-[0.14em] text-white/55">
              <Crosshair className="size-3" aria-hidden="true" /> AZ {cameraAzimuth.toFixed(2)}° · EL{" "}
              {cameraElevation.toFixed(2)}°
            </span>
          </div>
        </div>
      </div>

      <figcaption className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] leading-5 text-muted-foreground">
        <span className="font-semibold text-foreground/80">Demonstration value — not a measured hardware result.</span>
        <span>
          The viewport renders the simulated pipeline output: bounding box, estimated centre,
          alignment vector and confidence.
        </span>
      </figcaption>
    </figure>
  );
}
