import { StatusDot } from "@/components/common/Tags";
import { GuidanceArrow } from "@/components/tracking/GuidanceBadge";
import { useCameraFeed } from "@/hooks/use-camera-feed";
import { SIM, STATUS_COPY, type Telemetry, type TrackingStatus } from "@/lib/tracking-engine";
import { cn } from "@/lib/utils";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import {
  AlertTriangle,
  Crosshair,
  Focus,
  RefreshCw,
  ScanLine,
  Target,
  Video,
  VideoOff,
} from "lucide-react";
import { useState } from "react";

/**
 * The simulated camera feed.
 *
 * Everything drawn here is generated by the simulation engine. The viewport is
 * a virtual sensor: the overlay geometry is derived from the same telemetry the
 * numeric panels read, so the picture and the numbers always agree. An optional
 * real camera layer can be drawn *behind* the overlay; the geometry still comes
 * from the model, and every value remains labeled SIMULATED DATA.
 */
export function CameraViewport({
  telemetry,
  status,
  frameId,
  cameraAzimuth,
  cameraElevation,
}: {
  telemetry: Telemetry;
  status: TrackingStatus;
  frameId: string;
  cameraAzimuth: number;
  cameraElevation: number;
}) {
  const reduced = useReducedMotion();
  const copy = STATUS_COPY[status];
  const centreX = telemetry.center.x;
  const centreY = telemetry.center.y;
  const offsetX = telemetry.offsetPx.x;
  const offsetY = telemetry.offsetPx.y;
  const centreOfFrame = { x: SIM.frameWidth / 2, y: SIM.frameHeight / 2 };
  const [cameraEnabled, setCameraEnabled] = useState(false);
  const feed = useCameraFeed(cameraEnabled);
  const isLost = status === "lost";
  const isReacquiring = status === "reacquiring";
  const isLocked = status === "tracking" || status === "aligned";

  return (
    <figure className="flex flex-col gap-3">
      <div className={cn("clay-screen relative isolate overflow-hidden", "aspect-video w-full")}>
        {/* Real camera layer (behind the overlay, clearly marked). */}
        {cameraEnabled && (
          <video
            ref={feed.videoRef}
            muted
            playsInline
            autoPlay
            className="absolute inset-0 size-full object-cover"
            aria-hidden={!feed.live}
          />
        )}
        {/* Dim the sensor backdrop when a live video layer is on top. */}
        <div
          className={cn("absolute inset-0", feed.live && "opacity-45")}
          aria-hidden="true"
          style={{
            background:
              "radial-gradient(120% 90% at 50% 12%, color-mix(in oklch, var(--hud-cyan) 12%, transparent), transparent 60%), radial-gradient(90% 70% at 20% 100%, color-mix(in oklch, var(--hud-violet) 14%, transparent), transparent 65%), linear-gradient(180deg, oklch(0.235 0.038 266), oklch(0.19 0.032 266))",
          }}
        />
        {/* Extra veil so text stays legible over bright camera frames. */}
        {feed.live && <div className="absolute inset-0 bg-[oklch(0.2_0.03_266_/_42%)]" aria-hidden="true" />}

        {/* Radar-style reference rings */}
        <svg
          className="absolute inset-0 size-full opacity-[0.5]"
          viewBox="0 0 640 360"
          preserveAspectRatio="none"
          aria-hidden="true"
        >
          {[60, 120, 180].map((r) => (
            <circle
              key={r}
              cx={centreOfFrame.x}
              cy={centreOfFrame.y}
              r={r}
              fill="none"
              stroke="color-mix(in oklch, var(--hud-cyan) 30%, transparent)"
              strokeWidth={0.8}
              strokeDasharray="5 9"
            />
          ))}
          {Array.from({ length: 9 }).map((_, index) => (
            <line
              key={`v-${index}`}
              x1={index * 80}
              y1={0}
              x2={index * 80}
              y2={360}
              stroke="color-mix(in oklch, var(--hud-cyan) 16%, transparent)"
              strokeWidth={0.6}
            />
          ))}
          {Array.from({ length: 5 }).map((_, index) => (
            <line
              key={`h-${index}`}
              x1={0}
              y1={index * 90}
              x2={640}
              y2={index * 90}
              stroke="color-mix(in oklch, var(--hud-cyan) 16%, transparent)"
              strokeWidth={0.6}
            />
          ))}
          <line
            x1={centreOfFrame.x}
            y1={0}
            x2={centreOfFrame.x}
            y2={360}
            stroke="color-mix(in oklch, var(--hud-cyan) 55%, transparent)"
            strokeWidth={0.9}
          />
          <line
            x1={0}
            y1={centreOfFrame.y}
            x2={640}
            y2={centreOfFrame.y}
            stroke="color-mix(in oklch, var(--hud-cyan) 55%, transparent)"
            strokeWidth={0.9}
          />
        </svg>

        <div className="hud-scanlines absolute inset-0 opacity-60" aria-hidden="true" />

        {/* Acquisition sweep while the target is outside the frame centre */}
        {telemetry.inFov && status !== "aligned" && !isLost && !reduced && (
          <motion.div
            aria-hidden="true"
            className="absolute left-1/2 top-1/2 size-[520px] -translate-x-1/2 -translate-y-1/2 rounded-full"
            style={{
              background:
                "conic-gradient(from 0deg, color-mix(in oklch, var(--hud-cyan) 22%, transparent), transparent 40%)",
            }}
            animate={{ rotate: 360 }}
            transition={{ duration: 6, repeat: Infinity, ease: "linear" }}
          />
        )}

        {/* Tracking reticle — concentric rings anchored to the estimated target centre. */}
        {telemetry.inFov && isLocked && (
          <svg
            className="pointer-events-none absolute inset-0 size-full"
            viewBox="0 0 640 360"
            preserveAspectRatio="none"
            aria-hidden="true"
          >
            <circle
              cx={centreX}
              cy={centreY}
              r={44}
              fill="none"
              stroke="color-mix(in oklch, var(--chart-4) 42%, white)"
              strokeWidth={1}
              strokeDasharray="7 6"
              className={reduced ? "" : "animate-[spin_6s_linear_infinite] [transform-origin:var(--reticle-x)_var(--reticle-y)]"}
              style={{ "--reticle-x": `${centreX}px`, "--reticle-y": `${centreY}px` } as React.CSSProperties}
            />
            <circle
              cx={centreX}
              cy={centreY}
              r={22}
              fill="none"
              stroke="color-mix(in oklch, var(--chart-4) 68%, white)"
              strokeWidth={1.2}
              strokeDasharray="4 5"
            />
            {/* Small compass ticks on the reticle */}
            {[0, 90, 180, 270].map((a) => {
              const rad = (a * Math.PI) / 180;
              const r0 = 28;
              const r1 = 33;
              return (
                <line
                  key={a}
                  x1={centreX + Math.cos(rad) * r0}
                  y1={centreY + Math.sin(rad) * r0}
                  x2={centreX + Math.cos(rad) * r1}
                  y2={centreY + Math.sin(rad) * r1}
                  stroke="color-mix(in oklch, var(--chart-4) 78%, white)"
                  strokeWidth={1.4}
                />
              );
            })}
          </svg>
        )}
        {/* Re-acquisition reticle — amber, dashed, pulsing. */}
        {telemetry.inFov && isReacquiring && (
          <svg
            className="pointer-events-none absolute inset-0 size-full"
            viewBox="0 0 640 360"
            preserveAspectRatio="none"
            aria-hidden="true"
          >
            <circle
              cx={centreX}
              cy={centreY}
              r={38}
              fill="none"
              stroke="color-mix(in oklch, var(--chart-5) 70%, white)"
              strokeWidth={1.4}
              strokeDasharray="8 7"
              className={reduced ? "" : "animate-pulse"}
            />
            <circle
              cx={centreX}
              cy={centreY}
              r={18}
              fill="none"
              stroke="color-mix(in oklch, var(--chart-5) 55%, transparent)"
              strokeWidth={1}
              strokeDasharray="3 5"
            />
          </svg>
        )}

        {/* Sensor geometry — bbox + alignment vector */}
        {telemetry.inFov && (
          <svg
            className="absolute inset-0 size-full"
            viewBox="0 0 640 360"
            preserveAspectRatio="none"
            aria-hidden="true"
          >
            <line
              x1={centreOfFrame.x}
              y1={centreOfFrame.y}
              x2={centreX}
              y2={centreY}
              stroke={
                isLost
                  ? "color-mix(in oklch, var(--destructive) 78%, white)"
                  : isReacquiring
                    ? "color-mix(in oklch, var(--chart-5) 78%, white)"
                    : "color-mix(in oklch, var(--hud-violet) 85%, white)"
              }
              strokeWidth={1.6}
              strokeDasharray="6 5"
              opacity={isLost ? 0.55 : 1}
            />
            <rect
              x={telemetry.bbox.x}
              y={telemetry.bbox.y}
              width={telemetry.bbox.width}
              height={telemetry.bbox.height}
              fill={
                isLost
                  ? "color-mix(in oklch, var(--destructive) 10%, transparent)"
                  : isReacquiring
                    ? "color-mix(in oklch, var(--chart-5) 10%, transparent)"
                    : "color-mix(in oklch, var(--chart-4) 12%, transparent)"
              }
              stroke={
                isLost
                  ? "color-mix(in oklch, var(--destructive) 72%, white)"
                  : isReacquiring
                    ? "color-mix(in oklch, var(--chart-5) 72%, white)"
                    : "color-mix(in oklch, var(--chart-4) 78%, white)"
              }
              strokeWidth={2}
              rx={10}
              strokeDasharray={isReacquiring ? "7 5" : undefined}
            />
            {/* Corner brackets */}
            {[
              [0, 0, 1, 0],
              [0, 0, 0, 1],
              [1, 0, 0, 0],
              [0, 1, 0, 0],
            ].map(([ax, ay, bx, by], index) => (
              <line
                key={index}
                x1={telemetry.bbox.x + ax * 26}
                y1={telemetry.bbox.y + ay * 26}
                x2={telemetry.bbox.x + bx * 34}
                y2={telemetry.bbox.y + by * 34}
                stroke={
                  isLost
                    ? "color-mix(in oklch, var(--destructive) 80%, white)"
                    : isReacquiring
                      ? "color-mix(in oklch, var(--chart-5) 80%, white)"
                      : "color-mix(in oklch, var(--chart-4) 92%, white)"
                }
                strokeWidth={2.4}
              />
            ))}
            {/* Target centroid — central dot and crosshair */}
            <circle
              cx={centreX}
              cy={centreY}
              r={4}
              fill={
                isLost
                  ? "color-mix(in oklch, var(--destructive) 88%, white)"
                  : isReacquiring
                    ? "color-mix(in oklch, var(--chart-5) 88%, white)"
                    : "color-mix(in oklch, var(--chart-4) 92%, white)"
              }
            />
            <circle
              cx={centreX}
              cy={centreY}
              r={11}
              fill="none"
              stroke={
                isLost
                  ? "color-mix(in oklch, var(--destructive) 60%, white)"
                  : isReacquiring
                    ? "color-mix(in oklch, var(--chart-5) 60%, white)"
                    : "color-mix(in oklch, var(--chart-4) 70%, white)"
              }
              strokeWidth={1.2}
            />
            {/* Centroid crosshair lines (small). */}
            <line
              x1={centreX - 7}
              y1={centreY}
              x2={centreX + 7}
              y2={centreY}
              stroke="color-mix(in oklch, white 88%, transparent)"
              strokeWidth={1}
              opacity={0.9}
            />
            <line
              x1={centreX}
              y1={centreY - 7}
              x2={centreX}
              y2={centreY + 7}
              stroke="color-mix(in oklch, white 88%, transparent)"
              strokeWidth={1}
              opacity={0.9}
            />
          </svg>
        )}

        {/* Frame-centre crosshair — boresight reference */}
        <svg
          className="pointer-events-none absolute inset-0 size-full"
          viewBox="0 0 640 360"
          preserveAspectRatio="none"
          aria-hidden="true"
        >
          <circle
            cx={centreOfFrame.x}
            cy={centreOfFrame.y}
            r={26}
            fill="none"
            stroke="color-mix(in oklch, var(--hud-cyan) 70%, white)"
            strokeWidth={1.4}
          />
          <line
            x1={centreOfFrame.x - 12}
            y1={centreOfFrame.y}
            x2={centreOfFrame.x + 12}
            y2={centreOfFrame.y}
            stroke="color-mix(in oklch, var(--hud-cyan) 85%, white)"
            strokeWidth={1.4}
          />
          <line
            x1={centreOfFrame.x}
            y1={centreOfFrame.y - 12}
            x2={centreOfFrame.x}
            y2={centreOfFrame.y + 12}
            stroke="color-mix(in oklch, var(--hud-cyan) 85%, white)"
            strokeWidth={1.4}
          />
          {/* Outer corner brackets */}
          <path
            d="M18 46V18h28M594 18h28v28M622 314v28h-28M46 342H18v-28"
            fill="none"
            stroke="color-mix(in oklch, var(--hud-cyan) 45%, white)"
            strokeWidth={2}
          />
        </svg>

        {/* Tracking point readout, anchored to the estimated target centre */}
        {telemetry.inFov && (
          <motion.div
            className="absolute"
            style={{ x: "-50%" }}
            animate={{
              left: `${(centreX / SIM.frameWidth) * 100}%`,
              top: `${(centreY / SIM.frameHeight) * 100}%`,
            }}
            transition={{ duration: reduced ? 0 : 1 / SIM.fps, ease: "linear" }}
          >
            <div
              className={cn(
                "translate-y-[14px] whitespace-nowrap rounded-full px-2 py-0.5 font-mono text-[9.5px] font-semibold tracking-wide text-white",
                isLost
                  ? "bg-[color-mix(in_oklch,var(--destructive)_78%,black)]"
                  : isReacquiring
                    ? "bg-[color-mix(in_oklch,var(--chart-5)_74%,black)]"
                    : "bg-[color-mix(in_oklch,var(--chart-4)_82%,black)]",
              )}
            >
              {frameId} · {Math.round(telemetry.confidence * 100)}%
              {isLocked && " · LOCK"}
              {isReacquiring && " · RE-ACQUIRING"}
              {isLost && " · LOST"}
            </div>
          </motion.div>
        )}

        {/* HUD chrome — pointer-events disabled except for the camera toggle */}
        <div className="pointer-events-none absolute inset-0 p-3 sm:p-4">
          <div className="flex items-start justify-between gap-3">
            <div className="flex min-w-0 flex-col gap-1.5 text-left">
              <span className="hud-label !text-[9.5px] !text-[color-mix(in_oklch,var(--hud-cyan)_85%,white)]">
                Virtual sensor feed
              </span>
              <span className="flex items-center gap-2 font-mono text-[10.5px] uppercase tracking-widest text-white/85">
                <StatusDot tone={copy.tone} pulse={status !== "idle" && status !== "aligned"} />
                {copy.label}
              </span>
            </div>
            <div className="flex flex-col items-end gap-1.5">
              <span className="rounded-full border border-dashed border-[color-mix(in_oklch,var(--chart-5)_60%,transparent)] bg-black/25 px-2 py-0.5 font-mono text-[9px] uppercase tracking-[0.14em] text-[color-mix(in_oklch,var(--chart-5)_90%,white)] backdrop-blur">
                SIMULATED DATA
              </span>
              <span className="font-mono text-[10px] text-white/70">
                {SIM.frameWidth}×{SIM.frameHeight} · {telemetry.simulatedFps.toFixed(1)} fps ·{" "}
                {telemetry.simulatedLatencyMs.toFixed(1)} ms
              </span>
            </div>
          </div>

          {/* Centroid & guidance strip */}
          <div className="absolute bottom-3 right-3 hidden flex-col items-end gap-1 sm:flex sm:bottom-4 sm:right-4">
            <span className="flex items-center gap-1.5 rounded-full bg-black/28 px-2 py-1 font-mono text-[9.5px] uppercase tracking-[0.12em] text-white/80 backdrop-blur">
              <Target className="size-3" aria-hidden="true" /> Centroid {centreX.toFixed(1)},{" "}
              {centreY.toFixed(1)} px · AZ {telemetry.error.azimuthDeg >= 0 ? "+" : ""}
              {telemetry.error.azimuthDeg.toFixed(2)}° · EL{" "}
              {telemetry.error.elevationDeg >= 0 ? "+" : ""}
              {telemetry.error.elevationDeg.toFixed(2)}°
            </span>
            <span className="flex items-center gap-2 rounded-full bg-black/28 px-2 py-1 font-mono text-[10px] tracking-wide text-white/75 backdrop-blur">
              Slew <GuidanceArrow axis="azimuth" guidance={telemetry.guidance.azimuth} /> AZ{" "}
              <span className="mx-1 text-white/25">·</span>
              <GuidanceArrow axis="elevation" guidance={telemetry.guidance.elevation} /> EL
            </span>
          </div>

          <div className="absolute bottom-3 left-3 flex flex-col gap-1 sm:bottom-4 sm:left-4">
            <span className="flex items-center gap-1.5 font-mono text-[9.5px] uppercase tracking-[0.14em] text-white/55">
              <Focus className="size-3" aria-hidden="true" /> Boresight ΔX {offsetX.toFixed(1)} · ΔY{" "}
              {offsetY.toFixed(1)} px
            </span>
            <span className="flex items-center gap-1.5 font-mono text-[9.5px] uppercase tracking-[0.14em] text-white/55">
              <Crosshair className="size-3" aria-hidden="true" /> AZ {cameraAzimuth.toFixed(2)}° · EL{" "}
              {cameraElevation.toFixed(2)}°
            </span>
          </div>

          {/* Camera input toggle — the only interactive element in the HUD. */}
          <button
            type="button"
            onClick={() => setCameraEnabled((prev) => !prev)}
            className={cn(
              "pointer-events-auto absolute left-1/2 top-3 flex -translate-x-1/2 items-center gap-1.5 rounded-full px-2.5 py-1 font-mono text-[9.5px] uppercase tracking-[0.12em] backdrop-blur transition-colors sm:top-4",
              feed.live
                ? "bg-[color-mix(in_oklch,var(--chart-4)_22%,black)] text-white ring-1 ring-[color-mix(in_oklch,var(--chart-4)_45%,transparent)]"
                : "bg-black/30 text-white/75 ring-1 ring-white/15 hover:bg-black/40 hover:text-white",
            )}
            aria-pressed={cameraEnabled}
            title={feed.message}
          >
            {feed.live ? (
              <Video className="size-3" aria-hidden="true" />
            ) : (
              <VideoOff className="size-3" aria-hidden="true" />
            )}
            {feed.live ? "Camera on" : cameraEnabled ? "…connecting" : "Use camera input"}
          </button>
        </div>

        {/* Central status overlays — tracking lost / re-acquiring / searching / idle */}
        <AnimatePresence>
          {isLost && (
            <motion.div
              key="lost"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 flex items-center justify-center bg-[color-mix(in_oklch,var(--destructive)_18%,transparent)] backdrop-blur-[1px]"
            >
              <div className="clay flex max-w-[20rem] flex-col items-center gap-2 px-6 py-5 text-center">
                <span className="flex size-9 items-center justify-center rounded-full bg-[color-mix(in_oklch,var(--destructive)_18%,white)] text-destructive">
                  <AlertTriangle className="size-5" aria-hidden="true" />
                </span>
                <p className="font-mono text-xs font-bold uppercase tracking-[0.16em] text-destructive">
                  Tracking lost
                </p>
                <p className="text-xs leading-5 text-muted-foreground">
                  Target left the field of view. Re-centre or engage auto align to re-acquire.
                </p>
                <span className="rounded-full border border-dashed border-destructive/30 px-2 py-0.5 font-mono text-[9px] uppercase tracking-[0.14em] text-destructive">
                  SIMULATED EVENT
                </span>
              </div>
            </motion.div>
          )}
          {isReacquiring && (
            <motion.div
              key="reacquiring"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 flex items-center justify-center bg-[color-mix(in_oklch,var(--chart-5)_14%,transparent)] backdrop-blur-[1px]"
            >
              <div className="flex max-w-[18rem] flex-col items-center gap-2 text-center">
                <RefreshCw
                  className={cn("size-6 text-[color-mix(in_oklch,var(--chart-5)_78%,white)]", !reduced && "animate-spin")}
                  aria-hidden="true"
                  style={{ animationDuration: "1.4s" }}
                />
                <p className="font-mono text-xs font-bold uppercase tracking-[0.16em] text-[color-mix(in_oklch,var(--chart-5)_72%,black)]">
                  Re-acquiring
                </p>
                <p className="text-xs leading-5 text-white/70">
                  Target back in view — rebuilding confidence (≥ {Math.round(SIM.reacquireConfidence * 100)}%
                  to re-lock).
                </p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {!telemetry.inFov && !isLost && !isReacquiring && (
          <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
            <div className="flex flex-col items-center gap-2 text-center">
              <ScanLine
                className="size-6 text-[color-mix(in_oklch,var(--hud-cyan)_80%,white)]"
                aria-hidden="true"
              />
              <p className="font-mono text-[11px] uppercase tracking-[0.16em] text-white/85">
                {status === "idle" ? "Sensor idle" : "Target outside field of view"}
              </p>
              <p className="max-w-[15rem] text-[11px] leading-4 text-white/60">
                {status === "idle"
                  ? "Start tracking to begin the simulated acquisition sequence."
                  : "Coarse re-point required. Use re-centre or auto align."}
              </p>
            </div>
          </div>
        )}
      </div>

      <figcaption className="space-y-1.5">
        <p className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] leading-5 text-muted-foreground">
          <span className="rounded-full border border-dashed border-[color-mix(in_oklch,var(--chart-5)_50%,transparent)] px-2 py-0.5 font-mono text-[9.5px] uppercase tracking-[0.12em] text-[color-mix(in_oklch,var(--chart-5)_52%,black)]">
            SIMULATED DATA
          </span>
          <span className="font-semibold text-foreground/80">
            Demonstration value — not a measured hardware result.
          </span>
        </p>
        <p className="text-[11px] leading-5 text-muted-foreground">
          The viewport renders the simulated pipeline output: beacon bounding box, tracking
          reticle, estimated centroid, alignment vector and confidence. The camera toggle shows
          real video only as a backdrop; every numeric value remains simulated.
        </p>
        {feed.status !== "off" && (
          <p className="text-[11px] leading-5 text-muted-foreground">
            Camera: <span className="font-medium text-foreground/80">{feed.message}</span>
          </p>
        )}
      </figcaption>
    </figure>
  );
}
