import { ClayPanel } from "@/components/common/Clay";
import { PageHeader } from "@/components/common/Section";
import { TechBadge } from "@/components/common/Tags";
import { usePageMeta } from "@/lib/seo";
import { DISCLAIMERS } from "@/lib/site";
import { Scale } from "lucide-react";
import { Link } from "react-router";

const SECTIONS = [
  {
    id: "prototype",
    title: "Prototype disclaimer",
    body: [
      DISCLAIMERS.notIsro,
      "Drishti-Optik is an educational and demonstrative software prototype. It is provided as-is, without warranty of any kind, and its behaviour, interface and data model may change without notice.",
    ],
  },
  {
    id: "simulation",
    title: "Simulation disclaimer",
    body: [
      DISCLAIMERS.simulation,
      "Detection, tracking, confidence, bearing error, alignment progress and the reported update cadence are all produced by the simulation engine from a deterministic seed. They describe the model, not the physical world.",
      "The prototype constants — field of view, pixel mapping, slew rate, tolerance and range — are design assumptions chosen for legibility. They are not specifications, and they must not be quoted as performance figures.",
    ],
  },
  {
    id: "no-control",
    title: "No operational aerospace control",
    body: [
      DISCLAIMERS.noControl,
      "Nothing in this application initiates, authorises or influences any real pointing, acquisition or tracking activity. There is no command path to a terminal, ground station, satellite or any ISRO system.",
      "Any resemblance between the terminology used here and operational terminology is descriptive only, drawn from public literature.",
    ],
  },
  {
    id: "acceptable-use",
    title: "Acceptable use",
    body: [
      "Use the prototype to explore, review, teach or demonstrate the coarse alignment workflow. Do not present its output as a validated engineering result, and do not use it in any context where a real pointing decision depends on it.",
      "Do not attempt to disrupt the service, automate bulk submissions, probe or bypass the rate limits, or use the contact form to send unsolicited commercial messages.",
      "Do not upload or transmit confidential, export-controlled or personal data through the contact form or the assistant.",
    ],
  },
  {
    id: "accounts",
    title: "Accounts and content",
    body: [
      "You are responsible for activity under your session. Sign-in uses a one-time email code; keep access to that mailbox secure.",
      "Anonymous demo sessions are ephemeral and unsupported. History saved to an account can be cleared at any time from profile & settings.",
      "Questions submitted to Drishti AI are not engineering advice, and answers may be generated by a language model constrained to this prototype's knowledge base.",
    ],
  },
  {
    id: "limitations",
    title: "Limitations of liability",
    body: [
      "The prototype is not certified, verified or validated for any purpose. To the maximum extent permitted by law, the authors accept no liability for loss or damage arising from use of, or reliance on, this software or anything it displays.",
      "Availability is not guaranteed. The simulation continues to work locally if backend or assistant services are unavailable, but history may not be saved during an outage.",
    ],
  },
  {
    id: "ip",
    title: "Intellectual property",
    body: [
      "The application code, interface design and written copy of this prototype belong to its development team. Third-party open-source libraries are used under their respective licences.",
      "ISRO's name is used descriptively to identify the organisation named against the originating problem statement. No ISRO emblem, logo or official mark is used, and no endorsement is implied.",
      "Quoted or paraphrased technical material is attributed in the references list on the technology page.",
    ],
  },
  {
    id: "third-party",
    title: "Third-party services",
    body: [
      "Authentication email delivery, backend hosting and (when configured) language-model inference are provided by third parties and are subject to their own terms.",
      "Analytics is optional and consent-gated; declining it does not restrict any feature of the application.",
    ],
  },
  {
    id: "changes",
    title: "Changes to these terms",
    body: [
      "These terms may be updated as the prototype evolves. The revision date below reflects the current version; continued use after a change constitutes acceptance of it.",
      "Questions about these terms can be raised through the contact form.",
    ],
  },
];

export default function Terms() {
  usePageMeta({
    title: "Terms & Conditions | Drishti-Optik",
    description:
      "Prototype, simulation and no-operational-control disclaimers, acceptable use, accounts, liability, intellectual property and third-party terms for Drishti-Optik.",
    path: "/terms",
  });

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Terms & conditions"
        icon={Scale}
        title="The rules this prototype is offered under"
        description="Short, specific terms rather than boilerplate. The two things that matter most: this is a simulation, and it controls nothing."
        badge={<TechBadge tone="busy">Last updated September 2026</TechBadge>}
      />

      <div className="space-y-4">
        {SECTIONS.map((section, index) => (
          <ClayPanel key={section.id} id={section.id} className="scroll-mt-28 p-5 sm:p-7">
            <h2 className="flex items-center gap-3 text-lg font-semibold text-foreground">
              <span className="hud-label !text-[10px]">{String(index + 1).padStart(2, "0")}</span>
              {section.title}
            </h2>
            <div className="mt-3 space-y-3">
              {section.body.map((paragraph) => (
                <p key={paragraph} className="text-sm leading-7 text-muted-foreground">
                  {paragraph}
                </p>
              ))}
            </div>
          </ClayPanel>
        ))}
      </div>

      <ClayPanel size="sm" className="p-5 text-xs leading-6 text-muted-foreground">
        See the{" "}
        <Link to="/privacy" className="text-primary underline-offset-4 hover:underline">
          privacy policy
        </Link>{" "}
        for how data is handled, and the{" "}
        <Link to="/about" className="text-primary underline-offset-4 hover:underline">
          about page
        </Link>{" "}
        for the project's relationship to the originating problem statement.
      </ClayPanel>
    </div>
  );
}
